name: Node js app deploy to EKS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.27.0' # default is latest stable
      id: install

    - name: Configure AWS credentials
      continue-on-error: false
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ap-south-1
        role-to-assume: arn:aws:iam::857312989998:role/oidc-githubactions #change-----
        role-session-name: dev-deploy

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: devops-images
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo ${GITHUB_WORKSPACE}
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        echo "image=$REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Update kube config
      run: aws eks update-kubeconfig --name helm-ekscluster
    
    - name: Deploy nodejs helm chart to EKS
      run: |
        helm install nodeapp ./
